*&---------------------------------------------------------------------*
*& Include          ZSECURITY_BACKUP_PROG_SS
*&---------------------------------------------------------------------*
SELECTION-SCREEN: BEGIN OF BLOCK a1 WITH FRAME TITLE TEXT-100.
  SELECT-OPTIONS: s_r_name FOR lv_role_name ,
                  s_u_name FOR lv_usob_name .
  SELECTION-SCREEN: SKIP 1.

  PARAMETERS:     p_f_path TYPE rlgrap-filename.
*  SELECTION-SCREEN: SKIP 1.

SELECTION-SCREEN: END OF BLOCK a1.

SELECTION-SCREEN: BEGIN OF BLOCK g1 WITH FRAME TITLE TEXT-203.
  SELECT-OPTIONS: s_period FOR zworkload-period,
                  s_user FOR zworkload-account.
*  SELECTION-SCREEN: SKIP 1.
SELECTION-SCREEN: END OF BLOCK g1.

SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-101.
  SELECTION-SCREEN: SKIP 1.

  SELECTION-SCREEN: BEGIN OF BLOCK c1 WITH FRAME TITLE TEXT-103.
   SELECTION-SCREEN BEGIN OF LINE.
*   SELECTION-SCREEN: PUSHBUTTON 1(30) PB02 USER-COMMAND ONLI
*                  VISIBLE LENGTH 2.
    SELECTION-SCREEN: PUSHBUTTON 1(30) PB02 USER-COMMAND ONLI VISIBLE LENGTH 2.

    SELECTION-SCREEN POSITION 6.
    PARAMETERS: p_main_r AS CHECKBOX .
    SELECTION-SCREEN COMMENT 8(18) TEXT-130 FOR FIELD p_roles.
   SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 8.
      PARAMETERS: p_roles AS CHECKBOX .
      SELECTION-SCREEN COMMENT 10(18) TEXT-115 FOR FIELD p_roles.
      PARAMETERS: p_roles1 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 30(21) TEXT-116 FOR FIELD p_roles1.
      SELECTION-SCREEN POSITION 53.
      PARAMETERS: p_roles2 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 57(25) TEXT-117 FOR FIELD p_roles2.
    SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 8.
      PARAMETERS: p_t1 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 10(18) TEXT-118 FOR FIELD p_t1.
      PARAMETERS: p_t2 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 30(21) TEXT-119 FOR FIELD p_t2.
      SELECTION-SCREEN POSITION 53.
*      PARAMETERS: p_t3 AS CHECKBOX.
      PARAMETERS: p_tcodes AS CHECKBOX.
      SELECTION-SCREEN COMMENT 57(25) TEXT-112 FOR FIELD p_tcodes.
    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN: END OF BLOCK c1.

  SELECTION-SCREEN: BEGIN OF BLOCK d1 WITH FRAME TITLE TEXT-109.
**----------------------------------------------------------*
    SELECTION-SCREEN BEGIN OF LINE.
   SELECTION-SCREEN: PUSHBUTTON 1(30) PB03 USER-COMMAND ONLI
                  VISIBLE LENGTH 2.
    SELECTION-SCREEN POSITION 6.
    PARAMETERS:    p_tables AS CHECKBOX.
    SELECTION-SCREEN COMMENT 8(18) TEXT-131 FOR FIELD p_roles.
   SELECTION-SCREEN END OF LINE.
    SELECTION-SCREEN BEGIN OF LINE.
      SELECTION-SCREEN POSITION 8.
      PARAMETERS: p_t3 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 10(10) TEXT-120 FOR FIELD p_t3.
      SELECTION-SCREEN POSITION 23.
      PARAMETERS: p_t4 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 26(10) TEXT-121 FOR FIELD p_t4.
      PARAMETERS: p_t5 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 40(10) TEXT-122 FOR FIELD p_t5.
      SELECTION-SCREEN POSITION 53.
      PARAMETERS: p_t6 AS CHECKBOX.
      SELECTION-SCREEN COMMENT 57(10) TEXT-123 FOR FIELD p_t6.

    SELECTION-SCREEN END OF LINE.

  SELECTION-SCREEN: END OF BLOCK d1.
*---------------------------------------------------------*
  SELECTION-SCREEN: BEGIN OF BLOCK e1 WITH FRAME TITLE TEXT-111.

*    SELECT-OPTIONS: s_period FOR zworkload-period,
*                    s_user FOR zworkload-account.
**    SELECTION-SCREEN: SKIP 1.

    SELECTION-SCREEN: BEGIN OF LINE.
     SELECTION-SCREEN: PUSHBUTTON 1(30) PB01 USER-COMMAND ONLI
                  VISIBLE LENGTH 2.
      SELECTION-SCREEN POSITION 6.
      PARAMETERS: p_tusage AS CHECKBOX.
      SELECTION-SCREEN : COMMENT 8(20) TEXT-124.
      SELECTION-SCREEN POSITION 32.
      PARAMETERS: p_Merge AS CHECKBOX.
      SELECTION-SCREEN : COMMENT 34(15) TEXT-125.
      SELECTION-SCREEN POSITION 51.
      SELECTION-SCREEN: PUSHBUTTON 52(25) TEXT-200 USER-COMMAND p_button.
    SELECTION-SCREEN: END OF LINE.
  SELECTION-SCREEN: END OF BLOCK e1.

SELECTION-SCREEN: END OF BLOCK b1.

SELECTION-SCREEN: BEGIN OF BLOCK f1 WITH FRAME TITLE TEXT-201.
  SELECTION-SCREEN: PUSHBUTTON 1(30) PB04 USER-COMMAND ONLI
                  VISIBLE LENGTH 2.
  PARAMETERS: P1_file TYPE rlgrap-filename.
SELECTION-SCREEN: END OF BLOCK f1.

* SELECTION-SCREEN: BEGIN OF BLOCK f1 WITH FRAME TITLE TEXT-201.
*PARAMETERS: P1_file TYPE rlgrap-filename.
* SELECTION-SCREEN: END OF BLOCK f1.

*-----------------------------------------------------------*

AT SELECTION-SCREEN ON VALUE-REQUEST FOR p_f_path.
  DATA lv_f_path TYPE rlgrap-filename .
  CALL FUNCTION 'KD_GET_FILENAME_ON_F4'
    EXPORTING
*     PROGRAM_NAME  = SYST-REPID
*     DYNPRO_NUMBER = SYST-DYNNR
*     FIELD_NAME    = ' '
      static        = 'X'
      mask          = '*.xls'
*     FILEOPERATION = 'R'
*     PATH          =
    CHANGING
      file_name     = p_f_path
*     LOCATION_FLAG = 'P'
    EXCEPTIONS
      mask_too_long = 1
      OTHERS        = 2.
  IF sy-subrc <> 0.
* Implement suitable error handling here
  ENDIF.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P1_file.
  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      program_name  = syst-cprog
      dynpro_number = syst-dynnr
*     FIELD_NAME    = ' '
    IMPORTING
      file_name     = P1_file.


*-----------------------------------------------------------*
